
# Porty Configuration File

# Main forwarding configuration
listen_addr = "192.168.56.10"
listen_port = 1455
target_addr = "127.0.0.1"
target_port = 1455
max_connections = 100
buffer_size_kb = 8
log_requests = true
log_format = "default"

# Additional routes (optional)
[[routes]]
name = "web"
listen_port = 8080
target_addr = "127.0.0.1"
target_port = 80
enabled = false

[[routes]]
name = "api"
listen_port = 3000
target_addr = "127.0.0.1"
target_port = 3001
enabled = true
